# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

env:
  - TOX_ENV=py37-django-22
  - TOX_ENV=py36-django-22
  - TOX_ENV=py35-django-22
  - TOX_ENV=py37-django-30
  - TOX_ENV=py36-django-30
  - TOX_ENV=py35-django-30

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

before_script: npm install
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
